name: Build AOSP 8.1

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: تثبيت repo tool
      run: |
        curl https://storage.googleapis.com/git-repo-downloads/repo > repo
        chmod +x repo
        sudo mv repo /usr/local/bin/

    - name: تهيئة repo وتحميل السورس (بـ depth=1)
      run: |
        repo init -u https://android.googlesource.com/platform/manifest -b android-8.1.0_r93 --depth=1
        repo sync -j4 --depth=1

    - name: بناء AOSP
      run: |
        export USE_CCACHE=1
        export CCACHE_DIR=$HOME/.ccache
        ccache -M 50G
        source build/envsetup.sh
        lunch aosp_arm64-eng
        make clean
        make -j4
